parameter_config:
  experiment_name: glb_15min
  map_dir: /home/eat/cmf_v420_pkg/map/glb_15min
  hires_map_dir: /home/eat/cmf_v420_pkg/map/glb_15min/1min
  working_dir: /home/eat/CaMa-Flood-GPU
  inp_dir: ${parameter_config.working_dir}/inp/${parameter_config.experiment_name}/
  gauge_file: /home/eat/cmf_v420_pkg/map/glb_15min/GRDC_alloc.txt
  precision: float32
  save_gauge_only: false
  simulate_gauge_only: false

simulation_config:
  experiment_name: glb_15min
  working_dir: ${parameter_config.working_dir}
  out_dir: ${simulation_config.working_dir}/out/${simulation_config.experiment_name}/
  inp_dir: ${simulation_config.working_dir}/inp/${parameter_config.experiment_name}/
  states_file: null
  start_date: 2000-01-01
  end_date: 2000-12-31
  modules: [base, adaptive_time_step, bifurcation, log]
  time_step: 86400 # seconds
  default_num_sub_steps: 360
  statistics: 
    min: [river_outflow]
    max: [river_outflow]
    mean: [river_outflow, flood_outflow, bifurcation_outflow]

runoff_config:
  class_name: DailyBinDataset
  params:
    shape: [180, 360]
    unit_factor: 86400000 # mm/day divided by unit_factor to get m/s
    base_dir: /home/eat/cmf_v420_pkg/inp/test_1deg/runoff
    start_date: ${simulation_config.start_date}
    end_date: ${simulation_config.end_date}
    dtype: float32
    prefix: Roff____
    suffix: .one