working_dir: /home/eat/CaMa-Flood-GPU
experiment_name: glb_06min
out_dir: ${working_dir}/out/${experiment_name}/
inp_dir: ${working_dir}/inp/${experiment_name}/
map_dir: /home/eat/cmf_v420_pkg/map/glb_06min
hires_map_dir: /home/eat/cmf_v420_pkg/map/glb_06min/1min
states_file: None
start_date: 2000-01-01
end_date: 2000-12-31

runoff_dataset:
  class_name: DailyBinDataset
  params:
    shape: [180, 360]
    base_dir: /home/eat/cmf_v420_pkg/inp/test_1deg/runoff
    dtype: float32
    prefix: Roff____
    suffix: .one

runtime_flags:
  time_step: 86400 # seconds
  unit_factor: 86400000 # mm/day divided by unit_factor to get m/s
  default_sub_iters: 360
  precision: float32
  modules: [base, adaptive_time_step, log]
  device: gpu
  device_indices: [0]
  statistics: 
    min: [river_outflow]
    max: [river_outflow]
    mean: [river_outflow, flood_outflow]