experiment_name = "glb_15min"
input_file = "/home/eat/CaMa-Flood-GPU/inp/glb_15min/parameters.h5"
output_dir = "/home/eat/CaMa-Flood-GPU/out"
opened_modules = ["base", "adaptive_time", "bifurcation", "log"]
variables_to_save = ["river_outflow"]
precision = "float32"
time_step = 86400.0
default_num_sub_steps = 360
batch_size = 8
loader_workers = 2
output_workers = 2

runoff_dir = "/home/eat/cmf_v420_pkg/inp/test_1deg/runoff"
runoff_mapping_file = "/home/eat/CaMa-Flood-GPU/inp/glb_15min/runoff_mapping.npz"
runoff_shape = [180, 360]
start_date = "2000-01-01"
end_date = "2000-12-31"
unit_factor = 86400000
bin_dtype = "float32"
prefix = "Roff____"
suffix = ".one"
